# try:
#     x= 56
#     print(x)
# except NameError:
#     print("Variable x is undefined")
# except:
#     print('Something went wrong')


try:
    print(x)
except:
    print('Something went wrong!')
finally:
    print('We reached the end!')